admin_level = {'Afghanistan': 4,
                'Albania': 4,
                'Algeria': 4,
                'Andorra': 7,
                'Angola': 4,
                'Antigua and Barbuda': 4,
                'Argentina': 4,
                'Aruba': 7,
                'Australia': 4,
                'Austria': 4,
                'Azerbaijan': 4,
                'Bahamas': 6,
                'Bahrain': 4,
                'Bangladesh': 5,
                'Barbados': 6,
                'Belarus': 4,
                'Belgium': 4,
                'Belize': 4,
                'Benin': 4,
                'Bhutan': 4,
                'Bolivia': 4,
                'Bosnia and Herzegovina': 4,
                'Brazil': 4,
                'Brunei': 4,
                'Bulgaria': 4,
                'Burkina Faso': 4,
                'Burundi': 4,
                'Cambodia': 4,
                'Cameroon': 4,
                'Canada': 4,
                'Chad': 4,
                'Chile': 4,
                "China": 4,
                'Colombia': 4,
                'Congo-Kinshasa': 4,
                'Costa Rica': 4,
                'Country': 4,
                'Croatia': 6,
                'Cuba': 4,
                'Cyprus': 6,
                'Czech Republic': 4,
                "Côte d'Ivoire": 4,
                'Denmark': 4,
                'Dominican Republic': 4,
                'Ecuador': 4,
                'Egypt': 4,
                'El Salvador': 4,
                'Equatorial Guinea': 4,
                'Estonia': 6,
                'Ethiopia': 4,
                'Finland': 4,
                'France': 4,
                'Gabon': 4,
                'Gambia': 4,
                'Georgia': 4,
                'Germany': 4,
                'Ghana': 4,
                'Greece': 4,
                'Guatemala': 4,
                'Guinea': 4,
                'Guinée':4,
                'Haiti': 4,
                'Honduras': 4,
                'Hong Kong': 5,
                'Hungary': 4,
                'Iceland': 5,
                'India': 4,
                'Indonesia': 4,
                'Iran': 4,
                'Iraq': 4,
                'Ireland': 4,
                'Isle of Man': 6,
                'Israel': 4,
                'Palestine':4,
                'Italy': 4,
                'Japan': 4,
                'Jordan': 4,
                'Kenya': 4,
                'Kiribati': 7,
                'Kosovo': 4,
                'Laos': 4,
                'Latvia': 6,
                'Lebanon': 4,
                'Lesotho': 4,
                'Liberia': 4,
                'Libya': 4,
                'Lithuania': 4,
                'Luxembourg': 4,
                'Macau': 5,
                'Madagascar': 4,
                'Malawi': 4,
                'Malaysia': 4,
                'Mali': 4,
                'Malta': 6,
                'Mauritania': 4,
                'Mexico': 4,
                'Moldova': 4,
                'Montenegro': 6,
                'Morocco': 4,
                'Mozambique': 4,
                'Myanmar': 4,
                'Nepal': 4,
                'Netherlands': 4,
                'New Zealand': 4,
                'Nicaragua': 4,
                'Niger': 4,
                'Nigeria': 4,
                'North Korea': 4,
                'North Macedonia': 4,
                'Norway': 4,
                'Panama': 4,
                'Paraguay': 4,
                'Peru': 4,
                'Philippines': 4,
                'Poland': 4,
                'Portugal': 4,
                'Romania': 4,
                'Russia': 4,
                'Saint Lucia': 4,
                'San Marino': 7,
                'Senegal': 4,
                'Serbia': 4,
                'Sierra Leone': 4,
                'Slovakia': 4,
                'Slovenia': 4,
                'South Africa': 4,
                'South Korea': 4,
                'South Sudan': 4,
                'Spain': 4,
                'Suriname': 4,
                'Swaziland': 4,
                'Sweden': 4,
                'Switzerland': 4,
                'Syria': 4,
                'Taiwan': 4,
                'Tajikistan': 4,
                'Tanzania': 4,
                'ThailandSee': 4,
                'Togo': 4,
                'Tunisia': 4,
                'Turkey': 4,
                'Turkmenistan': 4,
                'Uganda': 4,
                'Ukraine': 4,
                'United Kingdom': 4,
                'United States': 4,
                'Uruguay': 4,
                'Uzbekistan': 4,
                'Vanuatu': 4,
                'Venezuela': 4,
                'Vietnam': 4,
                'Philippines': 4,
                'Central African Republic': 4,
                'French Polynesia': 6}